module.exports = [
  '<div class="article">',
    '<div class="title">',
      '<a name="name"></a>',
    '</div>',
    '<div class="inner">',
      '<div class="headers">',
        '<div class="header">',
          '<div class="key">commit</div>',
          '<div class="value commit"></div>',
        '</div>',
        '<div class="header">',
          '<div class="key">Author:</div>',
          '<div class="value author"></div>',
        '</div>',
        '<div class="header">',
          '<div class="key">Date:</div>',
          '<div class="value date"></div>',
        '</div>',
      '</div>',
      '<div class="body"></div>',
    '</div>',
  '</div>'
].join('\n')
