module.exports
= '<div class="preview">'
  + '<div class="label">recent articles</div>'
  + '<div class="image"></div>'
  + '<div class="title">'
    + '<a></a>'
  + '</div>'
  + '<div class="arrows">'
    + '<div class="left arrow"></div>'
    + '<div class="right arrow"></div>'
  + '</div>'
+ '</div>'
